<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
hado ghadi diri lihom tarjama bach ibano b francais 
 */
return [
    'Adr Ip' => 'Adresse IP',
    'Adr Mac Lan' => '',
    'Advanced search' => '',
    'Alimentation' => '',
    'Antivirus' => '',
    'Are you sure you want to delete this item?' => '',
    'Autre Config' => '',
    'Bios' => '',
    'Cable' => '',
    'Carte Mere' => '',
    'Code' => '',
    'Collaborator Name' => 'Nom Collaborateur',
    'Correspondant ID' => 'Correspondant',
    'Correspondants' => '',
    'Cpu' => '',
    'Create' => '',
    'Create Correspondants' => '',
    'Create Interventions' => '',
    'Create Lieu' => '',
    'Create Machines' => '',
    'Create Type Interventions' => '',
    'Created At' => '',
    'Date Intervention' => '',
    'Delete' => '',
    'Download' => '',
    'Gestion des interventions' => '',
    'Hdd' => '',
    'Home' => '',
    'ID' => '',
    'Intervention ID' => 'Intervention',
    'Interventions' => '',
    'Is Deleted' => '',
    'Lecteur' => '',
    'Lieu' => '',
    'Lieu ID' => 'Lieu',
    'Lieus' => '',
    'Machine ID' => 'Machine',
    'Machines' => '',
    'Name' => 'Nom',
    'Os' => '',
    'Parametres' => '',
    'Ram' => '',
    'Registre' => '',
    'Reset' => '',
    'Save to PDF' => '',
    'S N' => '',
    'Search' => '',
    'Text' => '',
    'Type' => '',
    'Type ID' => 'Type',
    'Type Interventions' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'Ventilateur' => 'Ventilateur',
];
